# Data-X Spring 2019: Homework 06 

## Name : Joseph Besgen
## SID : 3031839045
## Course (IEOR 135/290) : IEOR 135

### Machine Learning



In this homework, you will do some exercises with prediction. We will cover these algorithms in class, but this is for you to have some hands on with these in scikit-learn. You can refer - https://github.com/ikhlaqsidhu/data-x/blob/master/05a-tools-predicition-titanic/titanic.ipynb

Display all your outputs.


In [72]:
import numpy as np
import pandas as pd

In [73]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [74]:
#Read data & print the head
data = pd.read_csv("diabetesdata.csv")
data.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of Null values in each column and display it. **

In [75]:
data.isna().sum()/len(data['BP'])

TimesPregnant    0.000000
glucoseLevel     0.044271
BP               0.000000
insulin          0.000000
BMI              0.000000
Pedigree         0.000000
Age              0.042969
IsDiabetic       0.000000
dtype: float64

**3. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% as test.**


In [76]:
train_df, test_df = train_test_split(data, test_size=0.15, random_state=100)

In [77]:
print(train_df.shape)
print(test_df.shape)

(652, 8)
(116, 8)


**4. Display the means of the features in train and test sets. Replace the null values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature column separately for train and test. Display head of the dataframes.**

In [78]:
print("Train DF col means: \n", train_df.mean())
print("Test DF col means: \n", test_df.mean(axis=0))


train_df['TimesPregnant'] = train_df['TimesPregnant'].fillna(train_df['TimesPregnant'].mean())
train_df['glucoseLevel'] = train_df['glucoseLevel'].fillna(train_df['glucoseLevel'].mean())
train_df['BP'] = train_df['BP'].fillna(train_df['BP'].mean())
train_df['insulin'] = train_df['insulin'].fillna(train_df['insulin'].mean())
train_df['BMI'] = train_df['BMI'].fillna(train_df['BMI'].mean())
train_df['Pedigree'] = train_df['Pedigree'].fillna(train_df['Pedigree'].mean())
train_df['Age'] = train_df['Age'].fillna(train_df['Age'].mean())
train_df['IsDiabetic'] = train_df['IsDiabetic'].fillna(train_df['IsDiabetic'].mean())

test_df['TimesPregnant'] = test_df['TimesPregnant'].fillna(test_df['TimesPregnant'].mean())
test_df['glucoseLevel'] = test_df['glucoseLevel'].fillna(test_df['glucoseLevel'].mean())
test_df['BP'] = test_df['BP'].fillna(train_df['BP'].mean())
test_df['insulin'] = test_df['insulin'].fillna(test_df['insulin'].mean())
test_df['BMI'] = test_df['BMI'].fillna(train_df['BMI'].mean())
test_df['Pedigree'] = test_df['Pedigree'].fillna(test_df['Pedigree'].mean())
test_df['Age'] = test_df['Age'].fillna(train_df['Age'].mean())
test_df['IsDiabetic'] = test_df['IsDiabetic'].fillna(test_df['IsDiabetic'].mean())

Train DF col means: 
 TimesPregnant      3.797546
glucoseLevel     120.691318
BP                68.828221
insulin           78.743865
BMI               31.810890
Pedigree           0.469097
Age               33.375602
IsDiabetic         0.348160
dtype: float64
Test DF col means: 
 TimesPregnant      4.112069
glucoseLevel     122.821429
BP                70.663793
insulin           85.732759
BMI               33.013793
Pedigree           0.487500
Age               33.232143
IsDiabetic         0.353448
dtype: float64


/anaconda3/envs/data-x/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/anaconda3/envs/data-x/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/anaconda3/envs/data-x/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-do

In [79]:
train_df.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
458             10         148.0  84      237  37.6     1.001  51.0   
635             13         104.0  72        0  31.2     0.465  38.0   
457              5          86.0  68       71  30.2     0.364  24.0   
674              8          91.0  82        0  35.6     0.587  68.0   
277              0         104.0  64      116  27.8     0.454  23.0   

     IsDiabetic  
458           1  
635           1  
457           0  
674           0  
277           0

In [80]:
test_df.head()

TimesPregnant  glucoseLevel   BP  insulin   BMI  Pedigree   Age  \
173              1     79.000000   60       48  43.5     0.678  23.0   
253              0     86.000000   68        0  35.8     0.238  25.0   
207              5    162.000000  104        0  37.7     0.151  52.0   
737              8    122.821429   72        0  32.0     0.600  42.0   
191              9    123.000000   70       94  33.1     0.374  40.0   

     IsDiabetic  
173           0  
253           0  
207           1  
737           0  
191           0

**5. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [81]:
X_train = train_df.drop(columns=['IsDiabetic'])
X_test = test_df.drop(columns=['IsDiabetic'])
Y_train = train_df['IsDiabetic']
Y_test = test_df['IsDiabetic']

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)


(652, 7)
(116, 7)
(652,)
(116,)


**6. Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies. Try different hyperparameter values for these models and see if you can improve your accuracies.**

In [116]:
# 6a. Logistic Regression

logModel = LogisticRegression(C=5).fit(X_train, Y_train)
print('Training Accuracy: ', logModel.score(X_train,Y_train))
print('Test Accuracy: ', logModel.score(X_test,Y_test))

Training Accuracy:  0.7837423312883436
Test Accuracy:  0.7586206896551724


/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [117]:
# 6b. Perceptron

model = Perceptron(fit_intercept=True).fit(X_train, Y_train)
print('Training Accuracy: ', model.score(X_train,Y_train))
print('Test Accuracy: ', model.score(X_test,Y_test))

Training Accuracy:  0.4156441717791411
Test Accuracy:  0.45689655172413796


/anaconda3/envs/data-x/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [118]:
# 6c. Random Forest

model = RandomForestClassifier(n_estimators=100).fit(X_train, Y_train)
print('Training Accuracy: ', model.score(X_train,Y_train))
print('Test Accuracy: ', model.score(X_test,Y_test))

Training Accuracy:  1.0
Test Accuracy:  0.7068965517241379


**7. For your logistic regression model - **

**a . Compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your train set and display it. Also display the predicted class for those samples from your logistic regression model trained before. **


In [127]:
X_train_first10 = X_train.head(10)
Y_train_first10 = Y_train.head(10)

print("Predicted: \n", logModel.predict(X_train_first10))
print("Actual \n", np.array(Y_train_first10.T))

print("Log probability: \n", logModel.predict_log_proba(X_train_first10))

Predicted: 
 [1 0 0 0 0 1 0 0 0 0]
Actual 
 [1 1 0 0 0 0 0 0 0 0]
Log probability: 
 [[-1.88364399 -0.16491601]
 [-0.54173305 -0.87165011]
 [-0.1023215  -2.33036003]
 [-0.47692895 -0.96939257]
 [-0.09702638 -2.3808933 ]
 [-1.57286638 -0.2324993 ]
 [-0.18154873 -1.7956326 ]
 [-0.4420473  -1.02923335]
 [-0.4554559  -1.0055559 ]
 [-0.05180929 -2.98597853]]


**b . Now compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your test set and display it. Also display the predicted class for those samples from your logistic regression model trained before.
 (using the model trained on the training set)**


In [128]:
X_test_first10 = X_test.head(10)
Y_test_first10 = Y_test.head(10)

print("Predicted: \n", logModel.predict(X_test_first10))
print("Actual \n", np.array(Y_test_first10.T))

print("Log probability: \n", logModel.predict_log_proba(X_test_first10))

Predicted: 
 [0 0 1 1 0 1 1 0 1 0]
Actual 
 [0 0 1 0 0 1 1 1 1 0]
Log probability: 
 [[-0.21144058 -1.65766944]
 [-0.08729594 -2.48178182]
 [-1.1370723  -0.38677594]
 [-0.69462592 -0.69167062]
 [-0.64898998 -0.73934468]
 [-1.23859392 -0.34219655]
 [-3.29597707 -0.03773494]
 [-0.16054822 -1.90836127]
 [-1.99366382 -0.14640883]
 [-0.28019749 -1.40909022]]


**c . What can you interpret from the log probabilities and the predicted classes?**



**8. Is mean imputation is the best type of imputation (as we did in 4.) to use? Why or why not? What are some other ways to impute the data?**

This assumes that the data is centered around the mean. This might not be the best to use if the real data is skewed to one side of the mean (ex: if outliers affected the mean greatly where a couple large values caused the mean to increase). We could also use the median, create arbitrary values, or use 0 to impute the data.

## Extra Credit (2 pts) - MANDATORY for students enrolled in IEOR 290


**9.  Implement the K-Nearest Neighbours (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) algorithm for k=1 from scratch in python (do not use KNN from existing libraries). KNN uses Euclidean distance to find nearest neighbors. Split your dataset into test and train as before. Also fill in the null values with mean of features as done earlier. Use this algorithm to predict values for 'IsDiabetic' for your test set. Display your accuracy. **